### ISSUE TITLE
Am I running the wrong version for Grails 2.4.3?

### ISSUE THREAD

**Issue by lesiki** [mathifonseca/grails-slack#9]
Hi there, thanks for sharing this plugin, definitely a time-saver.

My BuildConfig has:

```
repositories {
	mavenRepo 'http://dl.bintray.com/mathifonseca/grails-plugins/'
}
dependencies {
	compile "org.grails.plugins:slack:3.0.0"
}

```

Mine is a Grails 2.4.3 app. On startup, I get the exception below. I'm wondering if there's a problem with the version I'm running? I have tried with version 2.0.0 and 3.0.0. Poking around in the maven repo and past gh issues, I can see the name migrated from `grails-slack`, but I tried this as well and got the same outcome. Exception disappears when the dependency is commented out.

Any tips for this? Is it maybe a known lack of compatibility with Grails 2.x?

> | Error Error executing script RunApp: grails/boot/config/GrailsAutoConfiguration (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NoClassDefFoundError: grails/boot/config/GrailsAutoConfiguration
	at _PluginDependencies$_run_closure2.doCall(_PluginDependencies.groovy:48)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at _GrailsPackage$_run_closure2.doCall(_GrailsPackage.groovy:57)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantMetaClass.processClosure(GantMetaClass.java:81)
	at org.codehaus.gant.GantMetaClass.processArgument(GantMetaClass.java:95)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:128)
	at RunApp$_run_closure1.doCall(RunApp:28)
	at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
	at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
	at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
	at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners$0.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:591)
	at gant.Gant.executeTargets(Gant.groovy:590)
Caused by: java.lang.ClassNotFoundException: grails.boot.config.GrailsAutoConfiguration

**Comment by lesiki** [comment]
I figured this out - yes, I was running the wrong version. [There's a grails 2.x branch](https://github.com/mathifonseca/grails-slack/tree/grails-2.x) in the repo, and the README there has clear instructions: install as a plugin, using the latest version published in the Grails plugin portal.

At time of writing, this seems to be

> compile ":slack:1.2.1"

Final note: in grails 2.x, as always, you want this in your 'plugins' closure, not 'dependencies'. No separate maven config required either.
